version: "2.4"
services:
    dotnet-node:
        image: akhilvatts/dotnet-sdk-nodejs:4.8-8.10.0
        build:
            context: .
            args:
                BASE_IMAGE: mcr.microsoft.com/dotnet/sdk:4.8
                NODE_VERSION: 8.10.0